"""
Metaflow compute backend scaffolding tool.

Generates a complete backend skeleton with all contract requirements
pre-filled and annotated.  This makes it hard to forget the requirements
that every backend gets wrong the first time.

Usage:
    python -m metaflow_backend_kit.scaffold my_backend
    metaflow-backend-scaffold my_backend [output_dir]

This creates:
    ./<name>/
        <name>_decorator.py     StepDecorator subclass
        <name>_executor.py      Job submission and log streaming
        <name>_client.py        API client skeleton
        plugins/__init__.py     Extension registration (mfextinit pattern)
        ux-tests-<name>.yml     GitHub Actions workflow skeleton

The generated files compile without modification.  Replace every
# TODO: BACKEND API comment with real backend-specific code.

Each generated file references BackendCapabilities (Cap) so you can
cross-check your implementation against the compliance test suite:

    from metaflow_backend_kit import Cap, REQUIRED

    SUPPORTED_CAPABILITIES = REQUIRED | {Cap.GPU}

    # Then run:
    metaflow-backend-validate ./<name>/
    metaflow-backend-test --backend my_backend
"""

import os
import sys


# ---------------------------------------------------------------------------
# Template helpers
# ---------------------------------------------------------------------------


def _classname(name: str) -> str:
    """Convert snake_case to PascalCase (e.g. 'my_backend' -> 'MyBackend')."""
    return "".join(w.capitalize() for w in name.split("_"))


def _write(path: str, content: str) -> None:
    os.makedirs(os.path.dirname(os.path.abspath(path)), exist_ok=True)
    with open(path, "w") as f:
        f.write(content)
    print(f"  wrote {path}")


# ---------------------------------------------------------------------------
# Template: StepDecorator subclass
# ---------------------------------------------------------------------------


def _generate_decorator(name: str) -> str:
    cls = _classname(name)
    NAME_UPPER = name.upper()
    return f'''\
"""Metaflow step decorator for {name} execution.

Generated by: python -m metaflow_backend_kit.scaffold {name}

BackendCapabilities contract (DO NOT remove these comments):

  Cap.ENV_PROPAGATION   — All METAFLOW_* env vars must reach the remote
                          container.  Build the env dict from
                          metaflow.metaflow_config_funcs.config_values() and
                          merge with _INITIAL_AUTH_ENV captured at import time.

  Cap.CODE_PACKAGE      — Code package must be uploaded to a URL reachable
                          from the remote container (not a local filesystem
                          path).  Use _save_package_once() to upload once per
                          flow run.

  Cap.RETRY_COUNT       — retry_count from runtime_step_cli is already
                          0-indexed.  Do NOT subtract 1 again.  Pass it
                          directly to --retry-count in the step CLI.

  Cap.DATASTORE_ACCESS  — Datastore credentials must be forwarded explicitly
                          into the remote container environment.  Ambient
                          credentials on the submitter machine do NOT transfer
                          automatically.

  Cap.INFRA_EXIT_CODE   — Infrastructure failures (quota errors, container
                          eviction, network timeouts) MUST exit with
                          METAFLOW_EXIT_DISALLOW_RETRY so Metaflow does not
                          consume the user\'s @retry budget.
                          User-code failures must return the real exit code.
                          See: docs/pitfalls/infra-vs-step-exit-code.md

  Cap.LOG_STREAMING     — stdout/stderr must be streamed in real time.
                          Use two background threads (one per stream) so
                          neither stream blocks the other.  See executor.

  Cap.MFLOG_CAPTURE     — Wire up export_mflog_env_vars + bash_capture_logs
                          + BASH_SAVE_LOGS in the remote command so Metaflow\'s
                          structured log format is preserved.

  Cap.CONDA             — Call self._ensure_conda_remote_command_aliases()
                          in step_init.  This patches CONDA_REMOTE_COMMANDS in
                          nflx-extensions so @conda steps get linux-64 packages
                          regardless of the submitter OS (macOS/aarch64).
                          Also pass --environment <type> to the step command.

  Cap.METADATA_SYNC     — Call _replay_task_metadata_to_service() in
                          task_finished so local metadata is synced to the
                          metadata service when running with local metadata.

  Cap.RESOURCES_MERGE   — Merge @resources decorator with max() per field in
                          step_init.  Without this, @resources is silently
                          ignored when @{name} is also present.

See metaflow_backend_kit.capabilities for the full list.
"""

from __future__ import annotations

import os
import platform
import sys
from importlib import import_module
from typing import Any, ClassVar, Dict, List, Optional

from metaflow.decorators import StepDecorator
from metaflow.exception import MetaflowException

# ---------------------------------------------------------------------------
# Auth env vars — captured at import time (credentials-import-time pitfall).
#
# WHY: If you read os.environ inside step_init or runtime_step_cli, the env
# may have been mutated or cleared (e.g. inside a remote Metaflow task that
# re-imports the decorator).  Capture the token values once at module load
# time and use them throughout the lifecycle.
# ---------------------------------------------------------------------------
_AUTH_VARS = [
    # TODO: BACKEND API — replace with your backend\'s credential env var names
    "{NAME_UPPER}_API_KEY",
    "{NAME_UPPER}_API_URL",
]
_INITIAL_AUTH_ENV: Dict[str, str] = {{
    k: v
    for k, v in ((var, os.environ.get(var)) for var in _AUTH_VARS)
    if v is not None
}}

_REMOTE_COMMAND_ALIASES = ("{name}",)


def _default_target_platform() -> str:
    """Detect the remote target platform for conda environment resolution.

    Returns "linux-aarch64" on ARM hosts (Apple Silicon, AWS Graviton),
    "linux-64" everywhere else.  This is the platform the remote container
    runs on — NOT the submitter OS.  Override with
    METAFLOW_{NAME_UPPER}_TARGET_PLATFORM if your container architecture
    differs from the submitter.
    """
    machine = platform.machine().lower()
    if machine in ("aarch64", "arm64"):
        return "linux-aarch64"
    return "linux-64"


def _get_run_time_limit_for_task(decorators: Any, timeout_attr: Any) -> Optional[int]:
    """Extract the effective timeout (seconds) for this task.

    Checks @timeout decorator first, then falls back to the decorator\'s own
    timeout attribute.  Returns None if no timeout is set.
    """
    # Check for @timeout decorator on the step
    for deco in decorators:
        if deco.name == "timeout":
            seconds = deco.attributes.get("seconds") or 0
            minutes = deco.attributes.get("minutes") or 0
            hours = deco.attributes.get("hours") or 0
            total = int(seconds) + int(minutes) * 60 + int(hours) * 3600
            if total > 0:
                return total
    # Fall back to our own timeout attribute
    if timeout_attr:
        return int(timeout_attr)
    return None


class {cls}Exception(MetaflowException):
    headline = "{name} error"


class {cls}Decorator(StepDecorator):
    """Run a Metaflow step on {name}.

    Parameters
    ----------
    cpu : float
        Number of CPUs (default: 1).
    memory : int
        Memory in MB (default: 1024).
    gpu : int
        Number of GPUs (default: 0).
    timeout : int or None
        Job timeout in seconds. None means no limit.
    image : str or None
        Docker image URL. None uses the backend\'s default image.
    env : dict
        Additional environment variables to set in the remote container.
    """

    name = "{name}"

    # Declare which capabilities this backend implements.
    # The compliance suite uses this to skip OPTIONAL tests you haven't built yet.
    # Start with REQUIRED; add optional caps as you implement them.
    from metaflow_backend_kit.capabilities import REQUIRED as _REQUIRED, Cap as _Cap
    SUPPORTED_CAPABILITIES = _REQUIRED  # | {{_Cap.GPU, _Cap.TIMEOUT, ...}}

    defaults: ClassVar[Dict[str, Any]] = {{
        "cpu": 1,
        "memory": 1024,
        "gpu": 0,
        "timeout": None,
        "image": None,
        "env": {{}},
    }}

    # REQUIRED (Cap.CONDA): declare that this backend supports conda environments.
    # Without this, @conda steps will not attempt linux-64 package resolution.
    supports_conda_environment = True

    @property
    def target_platform(self) -> str:
        """Target platform for conda environment resolution.

        Read from METAFLOW_{NAME_UPPER}_TARGET_PLATFORM env var so it can be
        overridden without code changes (e.g. when the remote container runs
        a different arch than the submitter).
        """
        return os.environ.get(
            "METAFLOW_{NAME_UPPER}_TARGET_PLATFORM", _default_target_platform()
        )

    # Class-level code-package state: shared across all decorator instances,
    # uploaded once per flow run (same pattern as BatchDecorator).
    package_url: ClassVar[Optional[str]] = None
    package_sha: ClassVar[Optional[str]] = None
    package_metadata: ClassVar[Optional[str]] = None
    _package: ClassVar[Any] = None  # set in runtime_init before task creation

    # -----------------------------------------------------------------------
    # Lifecycle hooks
    # -----------------------------------------------------------------------

    def _ensure_conda_remote_command_aliases(self, environment: Any) -> None:
        """Patch CONDA_REMOTE_COMMANDS in nflx-extensions to include {name}.

        REQUIRED (Cap.CONDA): Without this, @conda steps on a macOS/aarch64
        submitter receive a native-arch ResolvedEnvironment instead of
        linux-64.  The patch must be applied before the conda environment
        resolves packages for this step.
        """
        module_names = (
            "metaflow_extensions.netflix_ext.plugins.conda.conda_environment",
            "metaflow_extensions.netflix_ext.plugins.conda.conda_step_decorator",
        )
        for module_name in module_names:
            try:
                module = import_module(module_name)
            except (ImportError, ModuleNotFoundError):
                # Extension not installed — skip silently.
                continue
            # Any other exception means the module loaded but is broken; surface it.
            current = tuple(getattr(module, "CONDA_REMOTE_COMMANDS", ()))
            merged = tuple(dict.fromkeys([*current, *_REMOTE_COMMAND_ALIASES]))
            module.CONDA_REMOTE_COMMANDS = merged

    @classmethod
    def _save_package_once(cls, flow_datastore: Any, package: Any) -> None:
        """Upload the code package to the remote datastore exactly once.

        Stores package_url / package_sha / package_metadata on the class so
        that multiple @{name} steps in the same flow share a single upload.
        Pass package explicitly rather than relying on cls._package so this
        can be called from any context without depending on runtime_init order.
        """
        if {cls}Decorator.package_url is None:
            url, sha = flow_datastore.save_data(
                [package.blob], len_hint=1
            )[0]
            {cls}Decorator.package_url = url
            {cls}Decorator.package_sha = sha
            {cls}Decorator.package_metadata = package.package_metadata

    def step_init(
        self,
        flow: Any,
        graph: Any,
        step: str,
        decos: Any,
        environment: Any,
        flow_datastore: Any,
        logger: Any,
        stdout_path: Any = None,
        stderr_path: Any = None,
        max_user_code_retries: int = 0,
    ) -> None:
        # REQUIRED (Cap.CONDA): must be called before conda resolves packages.
        self._ensure_conda_remote_command_aliases(environment)

        self._step_name = step
        self.flow_datastore = flow_datastore
        self.environment = environment
        self.logger = logger
        self.attributes["env"] = dict(self.attributes.get("env") or {{}})

        # REQUIRED (Cap.RESOURCES_MERGE): merge @resources with max() per field.
        # Without this, @resources is silently ignored when @{name} is present.
        resources_deco = next(
            (d for d in decos if d.name == "resources"), None
        )
        if resources_deco is not None:
            for field in ("cpu", "memory", "gpu"):
                self_val = self.attributes.get(field) or 0
                res_val = resources_deco.attributes.get(field) or 0
                self.attributes[field] = max(self_val, res_val)

        # Derive the effective run-time limit from @timeout or our own attribute.
        self.run_time_limit = _get_run_time_limit_for_task(
            decos, self.attributes.get("timeout")
        )

        # REQUIRED: remote datastore needed so the container can persist artifacts.
        if flow_datastore.TYPE == "local":
            raise {cls}Exception(
                "@{name} requires a remote datastore (s3, azure, gs). "
                "Configure with: METAFLOW_DEFAULT_DATASTORE=s3\\n"
                "See https://docs.metaflow.org/scaling/remote-tasks/introduction"
            )

    def runtime_init(
        self, flow: Any, graph: Any, package: Any, run_id: str
    ) -> None:
        """Store flow-level state needed for code-package upload."""
        self.flow = flow
        self.graph = graph
        # Stash the package on the class so _save_package_once can reach it.
        {cls}Decorator._package = package
        self.run_id = run_id

    def runtime_task_created(
        self,
        task_datastore: Any,
        task_id: str,
        split_index: Any,
        input_paths: Any,
        is_cloned: bool,
        ubf_context: Any = None,
    ) -> None:
        """Upload the code package once, then record the task_id."""
        if not is_cloned:
            self._save_package_once(self.flow_datastore, {cls}Decorator._package)
        self.task_id = task_id

    def runtime_step_cli(
        self,
        cli_args: Any,
        retry_count: int,
        max_user_code_retries: int,
        ubf_context: Any,
    ) -> None:
        """Redirect execution through the {name} step CLI command.

        REQUIRED (Cap.RETRY_COUNT): retry_count is already 0-indexed.
        Do NOT subtract 1.  Pass it directly to --retry-count.

        REQUIRED (Cap.ENV_PROPAGATION): inject _INITIAL_AUTH_ENV and
        METAFLOW_RUNTIME_ENVIRONMENT into the command environment so the
        remote container can authenticate and identify its runtime.
        """
        # Guard: if we are already running inside a {name} container, do not
        # redirect again (prevents infinite recursion on re-import).
        if os.environ.get("METAFLOW_RUNTIME_ENVIRONMENT") == "{name}":
            return

        if retry_count <= max_user_code_retries:
            # Redirect the step command through the {name} CLI.
            cli_args.commands = ["{name}", "step"]
            cli_args.command_args.extend([
                self.package_metadata,
                self.package_sha,
                self.package_url,
            ])

            # Forward all non-env attributes as CLI options.
            _skip_keys = {{"env"}}
            cli_args.command_options.update({{
                k: v
                for k, v in self.attributes.items()
                if k not in _skip_keys
            }})

            # Serialize user env vars as repeated --env-var KEY=VALUE.
            # Also inject auth credentials captured at import time.
            user_env = dict(self.attributes.get("env") or {{}})
            for var in _AUTH_VARS:
                val = os.environ.get(var)
                if val is None:
                    val = _INITIAL_AUTH_ENV.get(var)
                if val is not None:
                    user_env.setdefault(var, val)

            # REQUIRED: tell the remote task which runtime it is running in.
            user_env["METAFLOW_RUNTIME_ENVIRONMENT"] = "{name}"

            if user_env:
                cli_args.command_options.setdefault("env-var", []).extend(
                    [f"{{k}}={{v}}" for k, v in user_env.items()]
                )

            cli_args.entrypoint[0] = sys.executable

    def task_pre_step(
        self,
        step_name: str,
        task_datastore: Any,
        metadata: Any,
        run_id: str,
        task_id: str,
        flow: Any,
        graph: Any,
        retry_count: int,
        max_user_code_retries: int,
        ubf_context: Any,
        inputs: Any,
    ) -> None:
        """Called inside the remote container before the user step body runs.

        Use this to emit job-level metadata (e.g. container ID, node name)
        via metadata.register_metadata().
        """
        self.metadata = metadata
        self.task_datastore = task_datastore
        # TODO: BACKEND API — emit backend-specific metadata, e.g.:
        #   from metaflow.metadata_provider import MetaDatum
        #   entries = [MetaDatum(
        #       field="{name}-job-id",
        #       value=os.environ.get("MY_BACKEND_JOB_ID", ""),
        #       type="{name}-job-id",
        #       tags=[f"attempt_id:{{retry_count}}"],
        #   )]
        #   metadata.register_metadata(run_id, step_name, task_id, entries)

    def task_finished(
        self,
        step_name: str,
        flow: Any,
        graph: Any,
        is_task_ok: bool,
        retry_count: int,
        max_retries: int,
    ) -> None:
        """Called inside the remote container after the user step body completes.

        REQUIRED (Cap.METADATA_SYNC): sync local metadata to the service when
        the metadata type is local.  Without this, task metadata written inside
        the remote container is lost after the container exits.
        """
        # TODO: BACKEND API — implement metadata sync here (Cap.METADATA_SYNC).
        # When the metadata provider type is "local", you must sync metadata
        # written inside the remote container back to the metadata service so
        # it is visible to the Metaflow client after the task finishes.
        #
        # See docs/pitfalls/metadata-sync.md for the recommended implementation
        # pattern and the helper utilities available in metaflow.metadata_provider.

    def task_exception(
        self,
        exception: BaseException,
        step_name: str,
        flow: Any,
        graph: Any,
        retry_count: int,
        max_retries: int,
    ) -> None:
        """Called inside the remote container when the user step raises an exception.

        Use this to emit failure metadata or clean up resources.
        """
        # TODO: BACKEND API — handle exception, e.g. emit failure metadata
        pass
'''


# ---------------------------------------------------------------------------
# Template: Executor
# ---------------------------------------------------------------------------


def _generate_executor(name: str) -> str:
    cls = _classname(name)
    NAME_UPPER = name.upper()
    return f'''\
"""Job submission and log streaming for {name}.

Generated by: python -m metaflow_backend_kit.scaffold {name}

IMPORTANT — infra vs step exit codes (Cap.INFRA_EXIT_CODE):
  Infrastructure failures (quota exceeded, container evicted, network error)
  MUST exit with METAFLOW_EXIT_DISALLOW_RETRY.  This tells Metaflow NOT to
  count the failure against the user\'s @retry budget.
  User-code failures (non-zero exit from the step itself) must be returned
  as-is so @retry can handle them.
  See: docs/pitfalls/infra-vs-step-exit-code.md

  Common exit codes to handle:
    137  — OOM kill (SIGKILL from the Linux OOM manager)
    124  — timeout (SIGKILL from a timeout wrapper like GNU timeout)
  Both should map to METAFLOW_EXIT_DISALLOW_RETRY.

Structure mirrors metaflow.plugins.aws.batch.batch.Batch.
"""

from __future__ import annotations

import sys
import threading
from typing import Any, Dict, Optional

from metaflow.exception import METAFLOW_EXIT_DISALLOW_RETRY

# TODO: BACKEND API — import your backend SDK here, e.g.:
#   from my_backend_sdk import Client, JobSpec


class {cls}Exception(Exception):
    """Raised for infrastructure-level {name} errors."""
    pass


class {cls}Executor:
    """Submit a Metaflow step to {name} and stream its logs.

    Usage (called from the {name} step CLI):

        executor = {cls}Executor(
            name=step_name,
            cmd=step_cmd,
            env=env_dict,
            attributes=decorator_attributes,
            echo=echo_fn,
        )
        sys.exit(executor.execute())

    The execute() method submits the job, streams logs, waits for completion,
    and returns the exit code.  Infrastructure errors cause sys.exit() with
    METAFLOW_EXIT_DISALLOW_RETRY rather than returning.
    """

    def __init__(
        self,
        name: str,
        cmd: str,
        env: Dict[str, str],
        attributes: Dict[str, Any],
        echo: Any,
    ) -> None:
        self._name = name
        self._cmd = cmd
        self._env = env
        self._attributes = attributes
        self._echo = echo
        self._job_id: Optional[str] = None

    def execute(self) -> int:
        """Submit, stream, wait, and return the exit code.

        Infrastructure errors (e.g. quota exceeded, missing image) are caught
        here and cause sys.exit(METAFLOW_EXIT_DISALLOW_RETRY) so that
        Metaflow does not retry a step that can never succeed on this infra.
        NotImplementedError is re-raised immediately so developer-facing stub
        errors are not mistaken for infrastructure failures.
        """
        try:
            self._submit_job()
        except NotImplementedError:
            raise
        except Exception as e:
            # Infrastructure error at submission time — disallow retry.
            # (A job that can\'t be submitted will never succeed on retry either.)
            self._echo(
                f"[{name}] Infrastructure error during job submission: {{e}}",
                stream="stderr",
                bad=True,
            )
            sys.exit(METAFLOW_EXIT_DISALLOW_RETRY)

        try:
            self._stream_logs()
            exit_code = self._wait()
        finally:
            # Always attempt to clean up the remote job on any exit path
            # (normal return, exception, or sys.exit via OOM/timeout branch).
            # _kill() is best-effort and must not raise.
            self._kill()

        # OOM (137) and timeout (124) are infrastructure problems; the user\'s
        # code did not produce a meaningful exit code.
        if exit_code in (137, 124):
            reason = "OOM kill" if exit_code == 137 else "timeout"
            self._echo(
                f"[{name}] Job exited with code {{exit_code}} ({{reason}}).  "
                "Disallowing retry (infra failure).",
                stream="stderr",
                bad=True,
            )
            sys.exit(METAFLOW_EXIT_DISALLOW_RETRY)

        return exit_code

    # -----------------------------------------------------------------------
    # Internal helpers — fill in the TODO sections
    # -----------------------------------------------------------------------

    def _submit_job(self) -> None:
        """Submit the step command to {name} and record self._job_id.

        Should raise an exception on infrastructure errors (quota, auth, etc.)
        so that execute() can catch them and exit with METAFLOW_EXIT_DISALLOW_RETRY.

        Example:
            client = {cls}Client()
            self._job_id = client.submit(
                cmd=self._cmd,
                env=self._env,
                cpu=self._attributes.get("cpu", 1),
                memory=self._attributes.get("memory", 1024),
                gpu=self._attributes.get("gpu", 0),
                image=self._attributes.get("image"),
                timeout=self._attributes.get("timeout"),
            )
            self._echo(f"[{name}] Submitted job {{self._job_id}}", stream="stderr")
        """
        # TODO: BACKEND API — submit the job and set self._job_id
        raise NotImplementedError("_submit_job() not yet implemented")

    def _stream_logs(self) -> None:
        """Stream stdout and stderr from the remote job in real time.

        REQUIRED (Cap.LOG_STREAMING): use two background threads — one for
        stdout and one for stderr — so neither stream blocks the other.
        Both threads must be started before waiting for either to finish.

        Example:
            client = {cls}Client()

            def _read_stdout() -> None:
                try:
                    for line in client.logs(self._job_id, stream="stdout"):
                        self._echo(line.rstrip("\\n"), stream="stderr")
                except Exception:
                    pass

            def _read_stderr() -> None:
                try:
                    for line in client.logs(self._job_id, stream="stderr"):
                        self._echo(line.rstrip("\\n"), stream="stderr")
                except Exception:
                    pass

            t_out = threading.Thread(target=_read_stdout, daemon=True)
            t_err = threading.Thread(target=_read_stderr, daemon=True)
            t_out.start()
            t_err.start()
            t_out.join()
            t_err.join()
        """
        # TODO: BACKEND API — stream logs from the remote job
        raise NotImplementedError("_stream_logs() not yet implemented")

    def _wait(self) -> int:
        """Wait for the job to finish and return its exit code.

        Should block until the job reaches a terminal state (SUCCEEDED, FAILED,
        CANCELLED, etc.) and return the integer exit code.

        Example:
            client = {cls}Client()
            while True:
                status = client.status(self._job_id)
                if status.is_done:
                    return status.exit_code or 0
                import time; time.sleep(5)
        """
        # TODO: BACKEND API — poll/wait for job completion
        raise NotImplementedError("_wait() not yet implemented")

    def _kill(self) -> None:
        """Terminate the remote job.  Best-effort, never raises.

        Called on KeyboardInterrupt or when the Metaflow runtime decides the
        step should be cancelled.

        Example:
            if self._job_id is not None:
                try:
                    {cls}Client().kill(self._job_id)
                except Exception:
                    pass
        """
        # TODO: BACKEND API — terminate the job
        pass
'''


# ---------------------------------------------------------------------------
# Template: API client
# ---------------------------------------------------------------------------


def _generate_client(name: str) -> str:
    cls = _classname(name)
    NAME_UPPER = name.upper()
    return f'''\
"""API client skeleton for {name}.

Generated by: python -m metaflow_backend_kit.scaffold {name}

This module wraps the {name} API.  Import _INITIAL_AUTH_ENV from the
decorator so credentials are always the values captured at import time,
not whatever os.environ looks like at call time.
"""

from __future__ import annotations

import os
from typing import Any, Dict, Generator

# Import the credentials captured at module load time (import-time pitfall):
# reading os.environ inside __init__ would use the current env, which may
# have been cleared or mutated inside a remote Metaflow task.
from .{name}_decorator import _AUTH_VARS, _INITIAL_AUTH_ENV

# TODO: BACKEND API — import your backend SDK here, e.g.:
#   import my_backend_sdk


class {cls}Client:
    """Thin wrapper around the {name} API.

    Authentication is read from the environment at import time via
    _INITIAL_AUTH_ENV (captured in {name}_decorator.py).

    All methods raise exceptions on API errors — the caller (executor)
    is responsible for distinguishing infra errors from step errors.
    """

    def __init__(self) -> None:
        # Read auth from the import-time snapshot first, fall back to current env.
        self._creds: Dict[str, str] = {{}}
        for var in _AUTH_VARS:
            val = _INITIAL_AUTH_ENV.get(var)
            if val is None:
                val = os.environ.get(var)
            if val is not None:
                self._creds[var] = val

        # TODO: BACKEND API — initialise your SDK client here, e.g.:
        #   api_key = self._creds.get("{NAME_UPPER}_API_KEY", "")
        #   self._client = my_backend_sdk.Client(api_key=api_key)

    def submit(self, **kwargs: Any) -> str:
        """Submit a job and return the job ID.

        Keyword arguments typically include: cmd, env, cpu, memory, gpu,
        image, timeout.  Raise an exception on infra errors.

        Returns:
            str: The backend-assigned job ID.
        """
        # TODO: BACKEND API — submit the job
        raise NotImplementedError("submit() not yet implemented")

    def status(self, job_id: str) -> Any:
        """Return the current status of job_id.

        The returned object should expose at least:
            .is_done: bool
            .exit_code: int | None  (None if still running)

        TODO: BACKEND API — query job status
        """
        raise NotImplementedError("status() not yet implemented")

    def logs(
        self, job_id: str, stream: str = "stdout"
    ) -> Generator[str, None, None]:
        """Yield log lines from job_id in real time.

        stream: "stdout" or "stderr"

        TODO: BACKEND API — stream log lines from the running/finished job
        """
        raise NotImplementedError("logs() not yet implemented")
        yield  # make this a generator even before implementation

    def kill(self, job_id: str) -> None:
        """Terminate job_id.  Best-effort, should not raise.

        TODO: BACKEND API — cancel / terminate the job
        """
        # TODO: BACKEND API — kill the job
        pass
'''


# ---------------------------------------------------------------------------
# Template: {name}_cli.py  (CLI entry point)
# ---------------------------------------------------------------------------


def _generate_cli(name: str) -> str:
    cls = _classname(name)
    return f'''\
"""CLI entry point for {name} step execution.

Generated by: python -m metaflow_backend_kit.scaffold {name}

This module is registered as the "{name}" CLI group in plugins/__init__.py
via CLIS_DESC.  Metaflow calls `python flow.py {name} step ...` to dispatch
a step to the {name} compute backend.

Extend the @cli.command("step") handler below with any additional options
that your backend decorator adds to cli_args.command_options.
"""

from __future__ import annotations

import sys
from typing import Optional

import click

from .{name}_executor import {cls}Executor


@click.group()
def cli() -> None:
    """{name} compute backend commands."""
    pass


@cli.command("step")
@click.argument("step_name")
@click.option("--run-id", required=True)
@click.option("--task-id", required=True)
@click.option("--input-paths", required=True)
@click.option("--split-index", default=None)
@click.option("--retry-count", default=0, type=int)
@click.option("--max-user-code-retries", default=0, type=int)
@click.option("--code-package-sha", required=True)
@click.option("--code-package-url", required=True)
@click.option("--code-package-metadata", default="")
@click.option("--env-var", "env_vars", multiple=True)
@click.pass_context
def step(
    ctx: click.Context,
    step_name: str,
    run_id: str,
    task_id: str,
    input_paths: str,
    split_index: Optional[str],
    retry_count: int,
    max_user_code_retries: int,
    code_package_sha: str,
    code_package_url: str,
    code_package_metadata: str,
    env_vars: tuple,
) -> None:
    """Execute a single Metaflow step inside a {name} task."""
    # Parse --env-var KEY=VALUE pairs forwarded from runtime_step_cli.
    env: dict = {{}}
    for pair in env_vars:
        k, _, v = pair.partition("=")
        if k:
            env[k] = v

    # The step command is the same argv that Metaflow would run locally,
    # minus the "{name} step" prefix that we stripped when dispatching.
    step_cmd = [sys.argv[0]] + sys.argv[sys.argv.index("step") + 1 :]

    executor = {cls}Executor(
        name=step_name,
        cmd=step_cmd,
        env=env,
        # Pass decorator attributes down to the executor if needed:
        # attributes=...,
    )
    exit_code = executor.execute()
    sys.exit(exit_code)
'''


# ---------------------------------------------------------------------------
# Template: plugins/__init__.py  (mfextinit pattern)
# ---------------------------------------------------------------------------


def _generate_plugins_init(name: str) -> str:
    cls = _classname(name)
    return f'''\
# metaflow_extensions/{name}/plugins/__init__.py
#
# This file is auto-discovered by Metaflow\'s extension system.
#
# IMPORTANT: Do NOT add __init__.py to metaflow_extensions/ or
# metaflow_extensions/{name}/.  Those directories must be implicit namespace
# packages.  Adding __init__.py there breaks extension discovery and causes
# Deployer(flow).{name}() / @{name} to silently not exist.
#
# Reference: https://docs.metaflow.org/internals/extensions

from metaflow.extension_support.plugins import process_plugins  # noqa: F401

# Register the @{name} step decorator so `@{name}` works in flow files.
# Two leading dots navigate from metaflow_extensions.<pkg>.plugins up to
# metaflow_extensions.<pkg> where the decorator module lives.
STEP_DECORATORS_DESC = [
    ("{name}", "..{name}_decorator.{cls}Decorator"),
]

# Register the {name} CLI group so `python flow.py {name} step ...` works.
CLIS_DESC = [
    ("{name}", "..{name}_cli.cli"),
]

# process_plugins() merges the above lists into the Metaflow plugin registry.
process_plugins(globals())
'''


# ---------------------------------------------------------------------------
# Template: GitHub Actions workflow
# ---------------------------------------------------------------------------


def _generate_gha(name: str) -> str:
    return f"""\
name: Backend Tests - {name}

# Compliance and integration tests for the {name} compute backend.
# Generated by: python -m metaflow_backend_kit.scaffold {name}
#
# Add this workflow to .github/workflows/ after wiring up credentials.
# The compliance tests require metaflow-backend-kit as a test dependency.

on:
  push:
    branches:
      - master
      - "**/{name}/**"
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  backend-tests:
    name: "{name} backend tests"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install package and test dependencies
        run: |
          pip install --upgrade pip
          pip install -e ".[dev]" metaflow metaflow-backend-kit

      # TODO: add your backend\'s credentials as repository secrets and
      # expose them here, e.g.:
      #   env:
      #     {name.upper()}_API_KEY: ${{{{ secrets.{name.upper()}_API_KEY }}}}
      #     {name.upper()}_API_URL: ${{{{ secrets.{name.upper()}_API_URL }}}}

      - name: Validate backend implementation
        run: |
          metaflow-backend-validate .

      - name: Run compliance tests
        # TODO: add credentials via env: block above before enabling this step
        run: |
          metaflow-backend-test --backend {name}

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-{name}
          path: junit-{name}.xml
          if-no-files-found: ignore
"""


# ---------------------------------------------------------------------------
# Generator
# ---------------------------------------------------------------------------


def scaffold(name: str, output_dir: str = ".") -> None:
    """Generate backend skeleton files for the given backend name."""
    cls = _classname(name)
    subdir = os.path.join(output_dir, name)
    plugins_subdir = os.path.join(subdir, "plugins")

    files = {
        os.path.join(subdir, f"{name}_decorator.py"): _generate_decorator(name),
        os.path.join(subdir, f"{name}_executor.py"): _generate_executor(name),
        os.path.join(subdir, f"{name}_cli.py"): _generate_cli(name),
        os.path.join(subdir, f"{name}_client.py"): _generate_client(name),
        os.path.join(plugins_subdir, "__init__.py"): _generate_plugins_init(name),
        os.path.join(subdir, f"ux-tests-{name}.yml"): _generate_gha(name),
    }

    print(f"Scaffolding compute backend: {name!r} (class prefix: {cls})")
    print(f"Output directory: {os.path.abspath(subdir)}/")
    print()
    for filepath, content in files.items():
        _write(filepath, content)

    print()
    print("=" * 60)
    print("Next steps:")
    print("=" * 60)
    print()
    print(f"  1. cd {name}/")
    print()
    print(f"  2. Fill in all # TODO: BACKEND API sections in:")
    print(f"       {name}_decorator.py  — step_init(), runtime_step_cli()")
    print(f"       {name}_executor.py   — _submit_job(), _stream_logs(), _wait()")
    print(f"       {name}_client.py     — submit(), status(), logs(), kill()")
    print()
    print(f"  3. Place generated files in your extension package:")
    print(f"       metaflow_extensions/{name}/plugins/{name}_decorator.py")
    print(f"       metaflow_extensions/{name}/plugins/{name}_executor.py")
    print(f"       metaflow_extensions/{name}/plugins/{name}_client.py")
    print(f"       metaflow_extensions/{name}/plugins/__init__.py")
    print()
    print("  *** CRITICAL: metaflow_extensions/ must NOT have __init__.py ***")
    print("      It is an implicit namespace package. Adding __init__.py breaks")
    print(f"      extension discovery — @{name} will silently not exist.")
    print()
    print(f"  4. Install the package in development mode:")
    print(f"       pip install -e .")
    print()
    print(f"  5. Validate the implementation (catches common bugs without running tests):")
    print(f"       metaflow-backend-validate {name}/")
    print()
    print(f"  6. Run the compliance tests:")
    print(f"       metaflow-backend-test --backend {name}")
    print()
    print("Contract checklist (things every backend gets wrong):")
    print(f"  [ ] _AUTH_VARS captured at import time (not in step_init)  [Cap.ENV_PROPAGATION]")
    print(f"  [ ] _save_package_once uploads to remote URL (not local path) [Cap.CODE_PACKAGE]")
    print(f"  [ ] retry_count passed directly (already 0-indexed)        [Cap.RETRY_COUNT]")
    print(f"  [ ] infra errors exit METAFLOW_EXIT_DISALLOW_RETRY          [Cap.INFRA_EXIT_CODE]")
    print(f"  [ ] two log-streaming threads (stdout + stderr)             [Cap.LOG_STREAMING]")
    print(f"  [ ] _ensure_conda_remote_command_aliases() called           [Cap.CONDA]")
    print(f"  [ ] @resources merged with max() per field in step_init     [Cap.RESOURCES_MERGE]")
    print(f"  [ ] _replay_task_metadata_to_service in task_finished       [Cap.METADATA_SYNC]")


def main() -> None:
    if len(sys.argv) < 2:
        print(__doc__)
        print("Usage: python -m metaflow_backend_kit.scaffold <name> [output_dir]")
        sys.exit(1)

    name = sys.argv[1].replace("-", "_")

    if not name.isidentifier():
        print(f"Error: {name!r} is not a valid Python identifier.", file=sys.stderr)
        print("Use only letters, digits, and underscores.", file=sys.stderr)
        sys.exit(1)

    output_dir = sys.argv[2] if len(sys.argv) > 2 else "."
    scaffold(name, output_dir)


if __name__ == "__main__":
    main()
